[project]
name = "expense-tracker-api"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.13.3",
    "asyncpg>=0.30.0",
    "bcrypt>=4.2.0",
    "fastapi[standard]>=0.115.4",
    "pyjwt[crypto]>=2.9.0",
    "sqlalchemy[asyncio]>=2.0.36",
]
